DriverOrario: DriverOrario.o Orario.o
	g++ -Wall -o DriverOrario Orario.o DriverOrario.o

ContoCorrente.o: DriverOrario.cpp Orario.hpp
	g++ -Wall -c Orario.cpp

DriverOrario.o: DriverOrario.cpp Orario.hpp
	g++ -Wall -c DriverOrario.cpp