DriverPoli: DriverPoli.o Poli.o
	g++ -Wall -o DriverPoli Poli.o DriverPoli.o

Poli.o: DriverPoli.cpp Poli.hpp
	g++ -Wall -c Poli.cpp

DriverPoli.o: DriverPoli.cpp Poli.hpp
	g++ -Wall -c DriverPoli.cpp