DriverVettori3D: DriverVettori3D.o Vettori3D.o
	g++ -Wall -o DriverVettori3D Vettori3D.o DriverVettori3D.o

Vettori3D.o: DriverVettori3D.cpp Vettori3D.hpp
	g++ -Wall -c Vettori3D.cpp

DriverVettori3D.o: DriverVettori3D.cpp Vettori3D.hpp
	g++ -Wall -c DriverVettori3D.cpp